version: '3.1'
services:
  devbox-db:
    image: 'healthsamurai/aidboxdb:13.2'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devbox
      PGDATA: /var/lib/postgresql/data/mnt
  devbox:
    image: 'healthsamurai/devbox:edge'
    platform: linux/amd64
    depends_on:
      - devbox-db
    ports:
      - '${AIDBOX_PORT:-8085}:${AIDBOX_PORT:-8085}'
    env_file:
      - .env
volumes:
  pgdata:
