name: Build

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      - run: npm run cov:send

      - name: Send Telegram notifications (success)
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🟢 Build succeeded: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
            By [${{github.event.push.sender.login}}](${{github.event.push.sender.url}})
          disable_web_page_preview: true

      - name: Send Telegram notifications (failure)
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🔴 Build failed: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
            By [${{github.event.push.sender.login}}](${{github.event.push.sender.url}})
          disable_web_page_preview: true
